name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
  test-member:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
      BATON_ENTERPRISE_TOKEN: "${{ secrets.BATON_ENTERPRISE_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-slack-enterprise
        run: go build ./cmd/baton-slack-enterprise
      - name: Test member workspace role sync and provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-slack-enterprise
          baton-entitlement: "${{ vars.WORKSPACE_ROLE_MEMBER_ENTITLEMENT }}"
          baton-principal: "${{ vars.WORKSPACE_ROLE_MEMBER_PRINCIPAL }}"
          baton-principal-type: 'user'
  test-admin:
    needs: [test-member]
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
      BATON_ENTERPRISE_TOKEN: "${{ secrets.BATON_ENTERPRISE_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-slack-enterprise
        run: go build ./cmd/baton-slack-enterprise
      - name: Test admin workspace role sync and provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-slack-enterprise
          baton-entitlement: "${{ vars.WORKSPACE_ROLE_ADMIN_ENTITLEMENT }}"
          baton-principal: "${{ vars.WORKSPACE_ROLE_ADMIN_PRINCIPAL }}"
          baton-principal-type: 'user'
  test-owner:
    needs: [test-member, test-admin]
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
      BATON_ENTERPRISE_TOKEN: "${{ secrets.BATON_ENTERPRISE_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-slack-enterprise
        run: go build ./cmd/baton-slack-enterprise
      - name: Test owner workspace role sync and provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-slack-enterprise
          baton-entitlement: "${{ vars.WORKSPACE_ROLE_OWNER_ENTITLEMENT }}"
          baton-principal: "${{ vars.WORKSPACE_ROLE_OWNER_PRINCIPAL }}"
          baton-principal-type: 'user'
  test-enterprise-roles:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
      BATON_ENTERPRISE_TOKEN: "${{ secrets.BATON_ENTERPRISE_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-slack-enterprise
        run: go build ./cmd/baton-slack-enterprise
      - name: Test enterprise role sync and provisioning
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-slack-enterprise
          baton-entitlement: "${{ vars.ENTERPRISE_ROLE_ENTITLEMENT }}"
          baton-principal: "${{ vars.ENTERPRISE_ROLE_PRINCIPAL }}"
          baton-principal-type: 'user'